--- 
- name: boot server 
  hosts: localhost 
  gather_facts: false
  vars:
    vm_password: Password123!

  tasks: 
    - name: boot the server 
      azure_rm_virtualmachine:
        ad_user: masteryadmin@example.com
        password: < insert your ad password here >
        resource_group: mastery
        name: mastery1
        admin_username: fedora
        admin_password: "{{ vm_password }}"
        vm_size: Standard_B1s
        image:
          offer: fedora
          publisher: tunnelbiz
          sku: fedora29
          version: latest
        plan:
          name: fedora29
          product: fedora
          publisher : tunnelbiz
      register: newserver
      changed_when: true

    - name: show floating ip 
      debug: 
        var: newserver.ansible_facts.azure_vm.properties.networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.publicIPAddress.properties.ipAddress

    - name: Wait for SSH to come up
      wait_for_connection:
        delay: 1
        timeout: 320

    - name: add new server 
      add_host: 
        name: "mastery1" 
        ansible_ssh_host: "{{ newserver.ansible_facts.azure_vm.properties.networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.publicIPAddress.properties.ipAddress }}"
        ansible_ssh_user: "fedora"
        ansible_ssh_pass: "{{ vm_password }}"
        ansible_become_pass: "{{ vm_password }}"

- name: configure server
  hosts: mastery1
  gather_facts: false

  tasks:
    - name: install python 
      raw: "dnf install -y python python2-dnf" 
      become: "yes"

    - name: install imagemagick
      dnf:
        name: "ImageMagick"
      become: "yes"
      changed_when: true