---
# tasks file for nginx

- name: Install Nginx
  ansible.builtin.package:
    name: nginx
    state: present
  become: yes

- name: Get Nginx Version
  ansible.builtin.command: /usr/sbin/nginx -V
  register: nginx_version_raw
  changed_when: false

- name: Extract Nginx Version
  ansible.builtin.set_fact:
    nginx_version: "{{ nginx_version_raw.stderr | regex_search('nginx version: nginx/([0-9.]+)', '\\1') | first }}"

- name: Create Facts Folder
  ansible.builtin.file:
    path: /etc/ansible/facts.d
    state: directory
    mode: '0755'
  become: yes

- name: Save Fact
  ansible.builtin.copy:
    content: |
      {
        "version": "{{ nginx_version }}"
      }
    dest: /etc/ansible/facts.d/nginx.fact
    mode: '0644'
  become: yes

- name: Start and Enable Nginx
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: yes
  become: yes

- name: Include node configuration if nginx_mode is 'node'
  ansible.builtin.include_tasks: node.yml
  when: nginx_mode == "node"

- name: Include load balancer configuration if nginx_mode is 'lb'
  ansible.builtin.include_tasks: lb.yml
  when: nginx_mode == "lb"
