---
- name: Start Docker
  hosts: all
  remote_user: ec2-user
  become: yes
  become_method: sudo
  become_user: root
  tasks:
    - name: Ensure Docker is installed and started
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Install Docker (RedHat-based systems)
      ansible.builtin.yum:
        name: docker
        state: present
      when: ansible_facts['os_family'] == 'RedHat'

    - name: Install Docker (Ubuntu-based systems)
      ansible.builtin.apt:
        name: docker.io
        state: present
      when: ansible_facts['os_family'] == 'Debian'

  roles:
    - Docker
    - dockerredhat
    - testcase

    

