---
- hosts: appserver
  user: test
  sudo: yes
  connection: ssh
  gather_facts: yes
  vars:
    distribution: RedHat
    nfsutils_pkg: nfs-utils
    nfslibs_pkg: nfs-utils-lib
    nfsserver_service: nfs-server
    nfslock_service: nfs-lock
    nfsmap_service: nfs-idmap
    rpcbind_service: rpcbind
    export_path: /var/share
    client_path: /mnt/remote

  tasks:
    - name: Install all the NFS Server Utilities, Services, and Libraries
      ansible.builtin.yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - "{{ nfsutils_pkg }}"
        - "{{ nfslibs_pkg }}"

    - name: Copy the export file to the remote server
      ansible.builtin.copy:
        src: files/exports.template
        dest: /etc/exports
        owner: root
        group: root
        mode: '0644'
      notify: 
        - StartServerServices
        - InstallClientPackages
        - CreateClientMount
        - ClientMountServerResource
        - TestServerAvailability

  handlers:
    - name: StartServerServices
      ansible.builtin.service:
        name: "{{ item }}"
        state: restarted
      with_items:
        - "{{ rpcbind_service }}"
        - "{{ nfsserver_service }}"
        - "{{ nfslock_service }}"
        - "{{ nfsmap_service }}"

    - name: InstallClientPackages
      ansible.builtin.yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - "{{ nfsutils_pkg }}"
        - "{{ nfslibs_pkg }}"
      delegate_to: 127.0.0.1
      notify: StartClientServices

    - name: StartClientServices
      ansible.builtin.service:
        name: "{{ item }}"
        state: restarted
      with_items:
        - "{{ rpcbind_service }}"
        - "{{ nfslock_service }}"
        - "{{ nfsmap_service }}"
      delegate_to: 127.0.0.1

    - name: CreateClientMount
      ansible.builtin.file:
        path: "{{ client_path }}"
        state: directory
        mode: '0755'
      delegate_to: 127.0.0.1

    - name: ClientMountServerResource
      ansible.builtin.shell: mount -t nfs tcox5.mylabserver.com:{{ export_path }} {{ client_path }}
      register: result
      delegate_to: 127.0.0.1

    - name: TestServerAvailability
      ansible.builtin.debug:
        var: result
