---
- name: Start MySQL
  hosts: all
  remote_user: ec2-user
  become: yes
  become_method: sudo
  become_user: root
  tasks:
    - name: Ensure MySQL is installed
      ansible.builtin.yum:
        name: mysql-server
        state: present
      when: ansible_facts['os_family'] == 'RedHat'

    - name: Ensure MySQL is installed (Ubuntu)
      ansible.builtin.apt:
        name: mysql-server
        state: present
      when: ansible_facts['os_family'] == 'Debian'

    - name: Ensure MySQL is started and enabled
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes
      when: ansible_facts['os_family'] == 'RedHat'

    - name: Ensure MySQL is started and enabled (Ubuntu)
      ansible.builtin.service:
        name: mysql
        state: started
        enabled: yes
      when: ansible_facts['os_family'] == 'Debian'

  roles:
    - mysql
