---
- hosts: apacheweb
  user: test
  sudo: yes
  connection: ssh
  gather_facts: yes
  vars:
    apache_pkg: httpd
    distribution: "{{ ansible_os_family }}" 
    apache_version: 2.4
    apache_dir: /var/www/sample
    apache_fqdn: tcox4.mylabserver.com

  tasks:
    - name: Install the Web Server Package
      ansible.builtin.yum:
        name: "{{ apache_pkg }}"
        state: latest

    - name: Create the web server directory
      ansible.builtin.file:
        path: "{{ apache_dir }}"
        state: directory
        mode: '0755'

    - name: Copy the Apache configuration file to remote host
      ansible.builtin.copy:
        src: files/httpd.conf.template
        dest: /etc/httpd/conf/httpd.conf
        owner: root
        group: root
        mode: '0644'

    - name: Create the VHOST.D Directory on the remote host
      ansible.builtin.file:
        path: /etc/httpd/vhost.d
        state: directory
        mode: '0755'

    - name: Copy and untar the source for the site
      ansible.builtin.unarchive:
        src: files/sitecode.tar.gz
        dest: "{{ apache_dir }}"
        remote_src: yes

    - name: Copy the default vhost configuration file
      ansible.builtin.copy:
        src: files/default.conf.template
        dest: /etc/httpd/vhost.d/default.conf
        owner: root
        group: root
        mode: '0644'
      notify:
        - StartHttpd
        - TestHttpd
        - DisplayResult

  handlers:
    - name: StartHttpd
      ansible.builtin.service:
        name: "{{ apache_pkg }}"
        state: started

    - name: TestHttpd
      ansible.builtin.shell: curl http://{{ apache_fqdn }}
      register: result

    - name: DisplayResult
      ansible.builtin.debug:
        var: result
