---
- name: configure SSH
  hosts: all
  vars:
    ssh_port: 2022
    allowed_users: ansible, root
    permit_root: no
  tasks: 
    - include_role:
        name: ssh-setup
      when: "ansible_facts['os_family'] == 'RedHat'"
    - name: set SELinux port context
      command: semanage port -a -t sshd_port_t -p tcp 2022
    - name: open port in firewall
      firewalld:
        port: 2022/tcp
        permanent: yes
        state: enabled
