---
- name: Configure sudo
  hosts: ansible2
  vars_files:
    - vars/defaults.yml
    - vars/groups.yml
  tasks:
    - name: Add groups
      ansible.builtin.group:
        name: "{{ item.groupname }}"
      loop: "{{ usergroups }}"

    - name: Add users
      ansible.builtin.user:
        name: "{{ item.username }}"
        groups: "{{ item.groups }}"
      loop: "{{ users }}"

    - name: Add SSH public keys
      ansible.builtin.authorized_key:
        user: "{{ item.username }}"
        key: "{{ lookup('file', 'files/' + item.username + '/id_rsa.pub') }}"
      loop: "{{ users }}"

    - name: Allow group members in sudo
      ansible.builtin.template:
        src: sudoers.j2
        dest: /etc/sudoers.d/sudogroups
        validate: 'visudo -cf %s'
        mode: 0440
