version: '3'

services:
  centos:
    image: "sbeliakou/trainings:centos-node-2"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    cap_add:
      - SYS_ADMIN
    expose:
    - 80
    ports:
     - 127.0.0.1:2200:22/tcp
     - 127.0.0.1:80:80/tcp