---
- name: Hashicorp Vault [Prerequisites]
  block:
    - name: Find root token file
      stat:
        path: "{{ vault_conf_path }}/root_token"
      register: token_file

    - name: Read root token
      slurp:
        src: "{{ vault_conf_path }}/root_token"
      when: token_file.stat.exists
      register: token

    - name: Set root token
      set_fact:
        root_token: "{{ token.content | b64decode | trim }}"
  no_log: true
  become: true
  tags: find_token

- name: Hashicorp Vault [Active Server]
  block:
    - name: Find active Vault
      uri:
        url: "http://127.0.0.1:8200/v1/sys/health"
        method: GET
        return_content: true
        headers:
          X-Vault-Token: "{{ root_token }}"
          X-Vault-Request: true
        status_code: [200, 429]
      register: vault_active
      until: vault_active.status in [200, 429]
      retries: 5
      delay: 5
      ignore_errors: yes
  no_log: true
  become: true
  environment: 
    VAULT_ADDR: "http://127.0.0.1:8200"
    VAULT_TOKEN: "{{ root_token }}"

- name: Hashicorp Vault [Auth Prerequisites]
  block:
    - name: Check enabled policies
      command: vault policy list
      register: active_policies
      ignore_errors: true
  when: vault_active.status == 200
  become: true
  environment: 
    VAULT_ADDR: "http://127.0.0.1:8200"
    VAULT_TOKEN: "{{ root_token }}"
  tags: auth_prerequisites

- name: Remove Policy
  block:
    - name: "Remove {{ tenant }} policy"
      command: vault policy delete "{{ tenant }}-policy"
      when: (vault_active.status == 200) and (active_policies.stdout | regex_search("^{{ tenant }}-policy$"))

    - name: Find policy file
      stat:
        path: "{{ vault_conf_path }}/{{ tenant }}-policy.hcl"
      register: policy_file

    - name: "Remove policy file from {{ vault_conf_path }}"
      file:
        path: "{{ vault_conf_path }}/{{ tenant }}-policy.hcl"
        state: absent
      when: policy_file.stat.exists
  become: true
  environment: 
    VAULT_ADDR: "http://127.0.0.1:8200"
    VAULT_TOKEN: "{{ root_token }}"
  tags: policy

- name: Remove Secret
  block: 
    - name: "Remove {{ tenant }} Auth0 Configuration"
      command: vault delete secret/customers/"{{ tenant }}"/auth0/configuration
  when: vault_active.status == 200
  become: true
  environment: 
    VAULT_ADDR: "http://127.0.0.1:8200"
    VAULT_TOKEN: "{{ root_token }}"
