---
- name: Copy the export file to the remote server
  ansible.builtin.copy:
    src: exports.template
    dest: /etc/exports
    owner: root
    group: root
    mode: '0644'
  notify:
    - InstallClientPackages
    - CreateClientMount
    - ClientMountServerResource
