---
- name: StartServerServices
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
  loop:
    - "{{ rpcbind_service }}"
    - "{{ nfsserver_service }}"
    - "{{ nfslock_service }}"
    - "{{ nfsmap_service }}"
