---
# tasks file for nginx

- name: Install Nginx
  ansible.builtin.package:
    name: nginx
  become: yes

- name: Get Nginx Version
  ansible.builtin.shell: /usr/sbin/nginx -V 2>&1 | grep 'nginx version' | awk -F/ '{print $2}'
  register: nginx_version
  changed_when: no

- name: Debugging Nginx Version
  ansible.builtin.debug:
    msg: "Nginx Version: {{ nginx_version.stdout }}"

- name: Create Facts Folder
  ansible.builtin.file:
    path: /etc/ansible/facts.d
    state: directory
  become: yes

- name: Save Fact
  ansible.builtin.copy:
    content: |
      {
        "version": "{{ nginx_version.stdout }}"
      }
    dest: /etc/ansible/facts.d/nginx.fact
  become: yes

- name: Debugging Nginx Fact File Path
  ansible.builtin.debug:
    msg: "Nginx fact file saved to /etc/ansible/facts.d/nginx.fact"

- name: Start Nginx
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: yes
  become: yes

- name: Debugging Nginx service status
  ansible.builtin.debug:
    msg: "Nginx service started and enabled."

- name: Include Node specific tasks
  ansible.builtin.include_tasks: node.yml
  when: "nginx_mode == 'node'"

- name: Include Load Balancer specific tasks
  ansible.builtin.include_tasks: lb.yml
  when: "nginx_mode == 'lb'"

- name: Debugging Nginx Mode
  ansible.builtin.debug:
    msg: "Nginx mode is set to: {{ nginx_mode }}"
