---
- name: configure switch
  hosts: mastery-switch1

  tasks:
  - name: bring up ports swp[1-3]
    nclu:
      template: |
        {% for interface in range(1,4) %}
        add interface swp{{interface}}
        add bridge bridge ports swp{{interface}}
        {% endfor %}
      commit: true

  - name: query swp1 interface
    nclu:
      commands:
        - show interface swp1
    register: interface

  - name: print interface status
    debug:
      var: interface
