---
---
- name: restart ufw
  ansible.builtin.service:
    name: ufw
    state: restarted

- name: restart firewalld
  ansible.builtin.service:
    name: firewalld
    state: restarted
    enabled: yes
