---
- name: install things 
  raw: dnf install -y python-dnf 

- name: use local python
  set_fact:
    ansible_python_interpreter: /usr/bin/python

- name: install things 
  dnf: 
    name: ['nginx', 'cowsay']

- name: configure nginx 
  lineinfile: 
    line: "daemon off;" 
    dest: /etc/nginx/nginx.conf 

- name: boop 
  shell: cowsay boop > /usr/share/nginx/html/index.html 
