- hosts: localhost
  gather_facts: no

  tasks:
  - name: module library/custom_module_bash.sh
    custom_module_bash:
  
  - name: module library/custom_module_python.py
    custom_module_python:
  
  - name: module library/custom_module_args_bash.sh
    custom_module_args_bash:
      msg: Hello from bash module

  - name: module library/custom_module_args_python.sh
    custom_module_args_python:
      msg: Hello from python module