- hosts: all

  pre_tasks:
  - yum: name=epel-release

  roles:
  - role: nginx
    nginx_mode: node



# Main Configuration in JSON (example):
# ```
# {
#     "variables": {
#         "variable1": "default value",
#         "variable2": "default value"
#     },
#     "builders": {
#         [
#             {
#                 "type": "builder-type",
#                 ...
#             }
#         ]
#     },
#     "post-processors": [
#         [
#             {
#                 "type": "post-processor type",
#                 ...
#             }
#         ]
#     ]
# }
# ```

# # Build Image
# $ packer build << packer_template.json >>

# # Build Image with Custom Variables
# $ packer build -var variable1=some_value << packer_template.json >>
# $ packer build -var-file=file_with_vars << packer_template.json >>

# # Restrict Builders (builder names/types: foo, bar, baz)
# $ packer build -only=foo,bar,baz << packer_template.json >>

# # Validate Template
# $ packer validate << packer_template.json >>

# packer build example.json

# docker run -d --privileged -P 80:80 centos-built-by-packer-with-ansible:2025