---
- name: Show lists also known as arrays
  hosts: ansible1.example.com
  vars_files:
    - vars/users-list
  tasks:
    - name: Print array values
      ansible.builtin.debug:
        msg: "User {{ item.username }} has homedirectory {{ item.homedir }} and shell {{ item.shell }}"
      loop: "{{ users }}"
    
    - name: Print the second array value
      ansible.builtin.debug:
        msg: "The second item is {{ users[1] }}"
