---
- name: Looping over Parallel Sets of Data Example
  hosts: localhost

  vars:
    letters: ['a', 'b', 'c', 'd']
    numbers: [1, 2, 3, 4]

  tasks:
    - name: Print letters with appropriate numbers
      ansible.builtin.debug:
        msg: "{{ item.0 }} and {{ item.1 }}"
      loop: "{{ letters | zip(numbers) }}"
