---
- name: Looping over Fileglobs Example
  hosts: localhost

  tasks:
    - name: Show full path to each file in folder
      debug:
        msg: "{{ item.path }}"
      ansible.builtin.find:
        paths: "files/"
        recurse: no
      loop: "{{ ansible_facts.files }}"
