---
- hosts: localhost

  tasks:
    - ansible.builtin.debug:
        msg: "{{ item.1 }} at position {{ item.0 }}"
      loop:
        - "apple"
        - "pear"
        - "banana"
        - "kiwi"
      loop_control:
        index_var: item
