---
- hosts: localhost

  tasks:
    - ansible.builtin.debug:
        msg: "User {{ item.0 }} will be added to group {{ item.1 }}"
      loop: "{{ lookup('ansible.builtin.product', ['alice', 'bob'], ['wheel', 'root']) }}"
