---
- name: Load the variables
  ansible.builtin.include_vars: '{{ ansible_os_family }}.yml'

- name: NGINX | Installing NGINX repo rpm el7 Architecture
  ansible.builtin.yum:
    name: http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'

- name: NGINX | Installing NGINX repo rpm
  ansible.builtin.yum:
    name: http://nginx.org/packages/rhel/6/noarch/RPMS/nginx-release-rhel-6-0.el6.ngx.noarch.rpm
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6'

- name: NGINX | Installing NGINX
  ansible.builtin.yum:
    name: nginx
    state: latest

- name: Determine if selinux is enabled
  ansible.builtin.command: getenforce
  register: getenforce
  ignore_errors: true
  changed_when: false

- name: Create Nginx User group
  ansible.builtin.group:
    name: '{{ nginx_group }}'
    state: present

- name: Creating Nginx Users and Group
  ansible.builtin.user:
    name: '{{ nginx_user }}'
    group: '{{ nginx_group }}'

- name: Configure the nginx settings directory.
  ansible.builtin.file:
    path: /etc/nginx
    state: directory
    owner: {{ nginx_user }}
    group: {{ nginx_group }}
    mode: '0755'
    recurse: yes

- name: Configure the Nginx system user's home directory.
  ansible.builtin.file:
    path: '{{ nginx_install_home }}'
    state: directory
    owner: {{ nginx_user }}
    group: {{ nginx_group }}
    mode: '0755'
