---
- include: install.yml

- name: Load the variables
  ansible.builtin.include_vars: '{{ ansible_os_family }}.yml'

- name: Copy the ntp.conf Jinja2 template file
  ansible.builtin.template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  notify:
    - restart ntp

- name: init.d changes Enabling the service
  ansible.builtin.service:
    name: '{{ ntpd }}'
    state: started
    enabled: yes
    pattern: '/ntp'

- name: View the NTP Settings
  ansible.builtin.command:
    cmd: cat /etc/ntp.conf
  register: out

- debug:
    var: out.stdout_lines

- name: ntpq Output
  ansible.builtin.command:
    cmd: ntpq -p
  register: out

- debug:
    var: out.stdout_lines
