---
- name: Remove Legacy Services Which are not Used in the Production System
  ansible.builtin.package:
    name: "{{ item }}"
    state: absent
  with_items:
    - telnet-server
    - telnet
    - rsh-server
    - rsh
    - ypserv
    - tftp
    - talk-server
    - xorg-x11-server-common
    - dhcp
    - net-snmp
