---
- name: Debian Family install the rkHunter, CheckrootKit, Clamv Antivirus
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
    force: yes
  loop:
    - clamav
    - rkhunter
    - chkrootkit
    - clamav-daemon
    - at
  when: ansible_facts.os_family == 'Debian'

- name: El6/7 install the rkHunter, CheckrootKit, Clamv Antivirus
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - epel-release
    - clamav
    - rkhunter
    - at
  when: ansible_facts.os_family == 'RedHat'

# Run and Verify the Results
- name: Run Clamscan Fire and Forget
  ansible.builtin.command: clamscan -i /tmp
  async: 45
  poll: 0
  register: clamscan

- name: CLAMV fire and Display Results
  ansible.builtin.async_status:
    jid: "{{ clamscan.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 30
- ansible.builtin.debug:
    var: job_result.stdout_lines

# Schedule the CLam Scan and Send Emails
- name: Run Clamv Once in a Week
  ansible.builtin.at:
    command: "clamscan -i /tmp | mail anish@packtpub.com"
    count: 1
    units: weeks
