---
- name: Load the variables
  ansible.builtin.include_vars:
    file: '{{ ansible_os_family }}.yml'

- name: Add banner information in sshd_config
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '#Banner /etc/issue.net'
    line: "Banner /etc/issue.net"

- name: Update ssh banner
  ansible.builtin.template:
    src: ssh-banner.conf
    dest: /etc/issue.net

- name: Restart ssh
  ansible.builtin.service:
    name: '{{ sshd }}'
    state: restarted
