---
- name: reset an F5
  hosts: localhost
  gather_facts: false

  tasks:
    - name: reset my F5
      bigip_config:
        reset: yes
        save: yes
        server: lb.mastery.example.com
        user: admin
        password: mastery
        validate_certs: no 
