---
- name: Include amazon.yml if the operating system is Amazon
  import_tasks: amazon.yml
  when: ansible_distribution == "Amazon"

- name: Include redhat.yml if the operating system is RedHat
  import_tasks: redhat.yml
  when: ansible_distribution == "RedHat"

- name: Include ubuntu.yml if the operating system is Ubuntu
  import_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"
