---
- name: Run the equivalent of "apt-get update" as a separate step
  ansible.builtin.apt:
    update_cache: yes

- name: Install Java 1.7 and some basic dependencies
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - unzip
    - openjdk-7-jre-headless
    - libselinux1
    - python-selinux

- name: Download JBoss from jboss.org
  ansible.builtin.get_url:
    url: "http://download.jboss.org/jbossas/7.1/jboss-as-7.1.1.Final/jboss-as-7.1.1.Final.zip"
    dest: /opt/jboss-as-7.1.1.Final.zip

- name: Extract archive
  ansible.builtin.unarchive:
    src: /opt/jboss-as-7.1.1.Final.zip
    dest: /usr/share/
    remote_src: yes

- name: Rename install directory
  ansible.builtin.command:
    cmd: /bin/mv /usr/share/jboss-as-7.1.1.Final /usr/share/jboss-as
  creates: /usr/share/jboss-as

- name: Copying standalone.xml configuration file
  ansible.builtin.template:
    src: standalone.xml
    dest: /usr/share/jboss-as/standalone/configuration/
  notify: restart jboss

- name: Add group "jboss"
  ansible.builtin.group:
    name: jboss

- name: Add user "jboss"
  ansible.builtin.user:
    name: jboss
    group: jboss
    home: /usr/share/jboss-as

- name: Change ownership of JBoss installation
  ansible.builtin.file:
    path: /usr/share/jboss-as/
    owner: jboss
    group: jboss
    state: directory
    recurse: yes

- name: Copy the init script
  ansible.builtin.copy:
    src: jboss-ubuntu-standalone.sh
    dest: /etc/init.d/jboss
    mode: '0755'

- name: Enable JBoss to be started at boot
  ansible.builtin.service:
    name: jboss
    enabled: yes
    state: started

- name: Ensure that firewalld is installed
  ansible.builtin.yum:
    name: firewalld
    state: present
  when: ansible_distribution_major_version == "7"

- name: Ensure that firewalld is started
  ansible.builtin.service:
    name: firewalld
    state: started
  when: ansible_distribution_major_version == "7"

- name: Deploy firewalld rules
  ansible.builtin.firewalld:
    immediate: yes
    port: "{{ item }}"
    state: enabled
    permanent: yes
  when: ansible_distribution_major_version == "7"
  loop:
    - "{{ http_port }}/tcp"
    - "{{ https_port }}/tcp"

handlers:
  - name: restart jboss
    ansible.builtin.service:
      name: jboss
      state: restarted
