---
- name: Install Oracle Java 8
  hosts: jenkins
  become: true

  tasks:
    - name: Install required dependencies
      ansible.builtin.apt:
        name: 
          - software-properties-common
          - dirmngr
        state: latest
        update_cache: yes

    - name: Install add-apt-repository
      ansible.builtin.apt:
        name: software-properties-common
        state: latest

    - name: Add Oracle Java Repository
      ansible.builtin.apt_repository:
        repo: deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main
        state: present
        filename: webupd8team-java

    - name: Add Oracle Java repository key
      ansible.builtin.apt_key:
        keyserver: keyserver.ubuntu.com
        id: EEA14886
        state: present

    - name: Accept Java 8 License
      ansible.builtin.debconf:
        name: oracle-java8-installer
        question: shared/accepted-oracle-license-v1-1
        value: "true"
        vtype: select

    - name: Update package cache
      ansible.builtin.apt:
        update_cache: yes
      ignore_errors: yes

    - name: Purge Oracle Java 8 installer (if previously installed)
      ansible.builtin.apt:
        name: oracle-java8-installer
        state: absent
        purge: yes

    - name: Install Oracle Java 8
      ansible.builtin.apt:
        name: 
          - ca-certificates
          - oracle-java8-installer
          - oracle-java8-set-default
        state: latest
