---
- name: Install Docker CE
  hosts: docker
  become: true

  vars:
    ansible_distribution_release: "{{ ansible_facts['lsb']['codename'] | default('trusty') }}"
    theuser: vagrant

  tasks:
    - name: Ensure old versions of Docker are removed
      ansible.builtin.apt:
        name:
          - docker
          - docker-engine
          - docker.io
        state: absent

    - name: Install required packages for Docker
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - software-properties-common
        state: latest
        update_cache: yes

    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker APT repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    - name: Install Docker CE
      ansible.builtin.apt:
        name: docker-ce
        state: present
        update_cache: yes
      notify: Restart Docker

    - name: Add user to Docker group
      ansible.builtin.user:
        name: "{{ theuser }}"
        append: yes
        groups: docker

  handlers:
    - name: Restart Docker
      ansible.builtin.systemd:
        name: docker
        state: restarted
        enabled: yes
