---
- name: Installing NFS Client
  hosts: nfs-clients
  become: true

  vars:
    nfsserver: "192.168.99.150"
    nfs_mountpoint: "/nfs"
    nfsexport: "/share"

  tasks:
    - name: Ensure NFS common is installed
      ansible.builtin.apt:
        name: nfs-common
        state: present
        update_cache: yes

    - name: Create mountable directory
      ansible.builtin.file:
        path: "{{ nfs_mountpoint }}"
        state: directory
        mode: '0777'
        owner: root
        group: root

    - name: Set mountpoints
      ansible.builtin.mount:
        name: "{{ nfs_mountpoint }}"
        src: "{{ nfsserver }}:{{ nfsexport }}"
        fstype: nfs
        opts: defaults,nobootwait
        dump: 0
        passno: 2
        state: mounted
