---
# ACL MODULE EXAMPLE
- hosts: localhost
  become: yes
  gather_facts: no
  tasks:
    - name: Get ACL Information on the /etc/test.acl.txt remote file
      ansible.builtin.acl:
        path: /etc/test.acl.txt
        entity: test
        etype: user
        permissions: "rw"
        state: present
      register: aclinfo

    - name: Debug ACL Information
      ansible.builtin.debug:
        var: aclinfo
