---
  - hosts: "{{ servers | default('all') }}"
    gather_facts: yes
    become: yes
    remote_user: "{{ remote_user | default('opc') }}"
    tasks:
      - name: Run command
        command: "{{ cmd }}"

#healthchecks