---
- hosts: appserver
  user: test
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks: 
    - name: Remove the dummy kernel module
      ansible.builtin.modprobe:
        name: dummy
        state: absent

    - name: Verify that the dummy module is removed
      ansible.builtin.command: lsmod | grep dummy
      register: lsmod_output
      changed_when: false
      failed_when: lsmod_output.rc == 0  # Fail if module still exists

    - name: Display module removal result
      ansible.builtin.debug:
        msg: "Kernel module 'dummy' successfully removed!"
