---
- hosts: localhost
  connection: local
  tasks:
    - name: First filter usage example
      ansible.builtin.debug:
        msg: "{{ 'test' | one_filter() }}"

    - name: Second filter usage example
      ansible.builtin.debug:
        msg: "{{ 'one' | another_filter('two','three') }}"
