---
- name: Conditionals test
  hosts: all
  tasks:
    - name: Install vsftpd if sufficient space on /var/ftp
      ansible.builtin.package:
        name: vsftpd
        state: latest
      loop: "{{ ansible_mounts }}"
      when: item.mount == "/var/ftp" and item.size_available > 100000000
