---
# Author: Farkhod Sadykov
- hosts: mysql-server
  become: true
  become_method: sudo
  connection: ssh
  vars:
    current_password: default([])
    new_password: Redhat2018
  tasks:
    - name: Install epel release for MySQL server
      ansible.builtin.yum:
        name: http://repo.mysql.com/mysql-community-release-el7-7.noarch.rpm
        state: present
      become: yes

    - name: Install MySQL Community Repo
      ansible.builtin.yum:
        name: mysql-server
        state: present
      become: yes

    - name: Install MySQL-python (required for the task to remove anonymous user)
      ansible.builtin.yum:
        name: MySQL-python
        state: present
      become: yes

    - name: Start MySQL server and enable it
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes
      become: yes

    - name: Change root user password on first run
      ansible.builtin.mysql_user:
        login_user: root
        login_password: ''
        name: root
        password: "{{ new_password }}"
        priv: "*.*:ALL,GRANT"
        host: "{{ item }}"
      loop:
        - "{{ ansible_hostname }}"
        - 127.0.0.1
        - ::1
        - localhost
      ignore_errors: true
