---
- hosts: localhost
  connection: local
  vars:
    myvar: "defined"
  tasks:
    - name: example of default filter
      ansible.builtin.debug:
        msg: "myvar value is {{ myvar | default('default') }}"

---
- hosts: localhost
  connection: local
  tasks:
    - name: example of default filter
      ansible.builtin.debug:
        msg: "myvar value is {{ myvar | default('default') }}"

---
- hosts: localhost
  connection: local
  tasks:
    - name: touch files with an optional mode
      ansible.builtin.file:
        dest: "{{ item.path }}"
        state: touch
        mode: "{{ item.mode | default(omit) }}"
      loop:
        - path: /tmp/foo
        - path: /tmp/bar
        - path: /tmp/baz
          mode: "0444"

---
- hosts: localhost
  connection: local
  tasks:
    - name: touch files with a mandatory mode
      ansible.builtin.file:
        dest: "{{ item.path }}"
        state: touch
        mode: "{{ item.mode | default('0444') }}"
      loop:
        - path: /tmp/foo
        - path: /tmp/bar
        - path: /tmp/baz
          mode: "0444"
