---
- name: Create user with encrypted password
  hosts: ansible2
  vars_prompt:
    - name: passw
      prompt: "Which password do you want to use?"
  vars:
    user: sharon
  tasks:
    - name: Hash the password
      ansible.builtin.debug:
        msg: "{{ passw | password_hash('sha512', 'myrandomsalt') }}"
      register: mypass

    - name: Show the hashed password
      ansible.builtin.debug:
        var: mypass

    - name: Create the user
      ansible.builtin.user:
        name: "{{ user }}"
        password: "{{ mypass.msg }}"
