---
- name: Using file module in Ansible 2.17
  hosts: localhost

  tasks:
    - name: Ensure directory exists with proper ownership and permissions
      ansible.builtin.file:
        path: /tmp/example_directory
        state: directory
        owner: vagrant
        mode: '0755'
        recurse: yes
      register: result

    - name: Show output from file module
      ansible.builtin.debug:
        var: result
