---
- hosts: all
  user: test
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Run the uptime command on all hosts and log it
      ansible.builtin.raw: /usr/bin/uptime >> /home/test/uptime.log
    
    - name: List the /var directory and log it (run once)
      ansible.builtin.raw: ls -al /var >> /home/test/dir.list
      run_once: true

    - name: Run on only one host
      ansible.builtin.raw: ls -al /var >> /home/test/dir.list
      run_once: true
      delegate_to: special_host

    - name: Run the task only if the file does not exist
      ansible.builtin.raw: ls -al /var >> /home/test/dir.list
      run_once: true
      when: ansible_facts['distribution'] == 'Ubuntu'
