---
- hosts: apacheweb
  user: test
  connection: ssh
  sudo: yes
  gather_facts: no
  tasks:
    - name: Run the system_uptime.sh script
      ansible.builtin.script: /home/test/Playbooks/system_uptime.sh creates=/home/test/uptime.log

    - name: Run a remote script
      ansible.builtin.script: /path/to/remote/script.sh

    - name: Run the script with arguments
      ansible.builtin.script: /home/test/Playbooks/system_uptime.sh
      args:
         chdir: /home/test/Playbooks/

