---
- hosts: apacheweb
  user: test
  sudo: yes
  gather_facts: no
  connection: ssh
  tasks:
    - name: Add the user called tstapache to the apache web client
      ansible.builtin.user:
        name: tstapache
        comment: "tst user"
        shell: /bin/bash
        groups: wheel
        append: yes
