---
- hosts: apacheweb
  sudo: yes
  gather_facts: no
  tasks:
    - name: Installing Apache Tomcat
      ansible.builtin.yum:
        name: tomcat
        state: installed

    - name: Waiting for Port 8080 to Listen
      ansible.builtin.wait_for:
        port: 8080
        state: started

    - name: Verifying Lynx Installation
      ansible.builtin.yum:
        name: lynx
        state: present
