---
- name: error handling
  hosts: all
  gather_facts: false

  tasks:
  - name: delete branch bad
    command: git branch -D badfeature
    args:
      chdir: /srv/app
    ignore_unreachable: true
  - name: important task
    debug:
      msg: It is important we attempt this task!
