---
- name: error handling
  hosts: localhost
  gather_facts: false

  tasks:
  - block:
      - name: delete branch bad
        command: git branch -D badfeature
        args:
          chdir: /srv/app
        register: gitout
        failed_when:
          - gitout.rc != 0
          - not gitout.stderr is search('branch.*not found')

      - name: this task is lost
        debug:
          msg: "I do not get seen"

    rescue:
      - name: cleanup task
        debug:
          msg: "I am cleaning up"

      - name: cleanup task 2
        debug:
          msg: "I am also cleaning up"

    always:
      - name: most important task
        debug:
          msg: "Never going to let you down"

  - name: task after block
    debug:
      msg: "Execution goes on"
