--- 
- name: error handling 
  hosts: localhost
  gather_facts: false 
 
  tasks: 
  - name: query sessions
    command: /sbin/iscsiadm -m session
    register: sessions
    failed_when: sessions.rc not in (0, 21) 
