--- 
- name: any errors fatal 
  hosts: failtest 
  gather_facts: false 
  force_handlers: true

  tasks:
  - name: run first
    debug:
      msg: "I am a change"
    changed_when: true
    when: inventory_hostname == play_hosts[-1]
    notify: critical handler
  - name: change a host
    fail:
      msg: "I am last"
    when: inventory_hostname == play_hosts[-1] 

  - name: never run
    debug:
      msg: "I should never be run"
    when: inventory_hostname == play_hosts[-1]

  handlers:
    - name: critical handler
      debug:
        msg: "I really need to run"
