---
- name: looping demo
  hosts: localhost
  gather_facts: false

  tasks:
  - name: create a directory
    file:
      path: /srv/whiskey/alpha
      state: directory
  - name: create another directory
    file:
      path: /srv/whiskey/beta
      state: directory
