---
- name: Relative path play
  hosts: localhost
  gather_facts: false

  vars_files:
    - a_vars_file.yaml

  tasks:
    - name: Who am I
      ansible.builtin.debug:
        msg: "I am mastery task"

    - name: Var from file
      ansible.builtin.debug:
        var: something

    - ansible.builtin.include_tasks: tasks/a.yaml
