---
- name: demo the template
  hosts: localhost
  gather_facts: false
  vars:
    data_dirs: ['/', '/foo', '/bar']
  tasks:
    - name: Render and display the template
      debug:
        msg: "{{ lookup('template', 'demo-for.j2') }}"
