---
- name: Testing the J2 Template Module
  hosts: apacheweb:debian
  connection: ssh
  user: test
  become: yes
  gather_facts: yes
  vars:
    userName: test
    userPassword: password123
    connectionType: SFTP
  tasks:
    - name: Install the configuration file customized for the system
      ansible.builtin.template:
        src: test.conf.j2
        dest: /home/test/test.conf
        owner: test
        group: test
        mode: '0750'
