---
- hosts: local
  become: true
  vars_files:
    - users.yml

  tasks:
    - name: Create users with home directory
      user:
        name: "{{ item.username }}"
        shell: /bin/bash
        createhome: yes
        comment: "Created with Ansible"
      loop: "{{ users }}"

    - name: Sudoers | Update sudoers file and validate
      lineinfile:
        path: /etc/sudoers
        insertafter: EOF
        line: "{{ item.username }} ALL=(ALL) NOPASSWD: ALL"
        regexp: "^{{ item.username }} .*"
        state: present
        validate: "visudo -cf %s"
      when: item.use_sudo | default(false) | bool
      loop: "{{ users }}"
