---
# AWS IAM MODULE EXAMPLE
- hosts: localhost
  connection: local
  remote_user: test
  become: yes
  gather_facts: no
  vars_files:
    - files/awscreds.yml

  tasks:
    - name: Create IAM Users
      amazon.aws.iam_user:
        aws_access_key: "{{ aws_id }}"
        aws_secret_key: "{{ aws_key }}"
        region: "{{ aws_region }}"
        name: "{{ item }}"
        state: present
        password: "password"
        password_reset_required: yes
        access_keys: yes
      with_items:
        - tmp1
        - tmp2
      register: output

    - name: Show the JSON Results
      ansible.builtin.debug:
        var: output
