---
# AWS S3 MODULE EXAMPLE
- hosts: localhost
  connection: local
  remote_user: test
  become: yes
  gather_facts: no
  vars_files:
    - files/awscreds.yml

  tasks:
    - name: Create an S3 Bucket
      amazon.aws.s3_bucket:
        aws_access_key: "{{ aws_id }}"
        aws_secret_key: "{{ aws_key }}"
        region: "{{ aws_region }}"
        name: ansiblebucket2
        state: present
        acl: public-read-write
      register: create_bucket

    - name: Copy the Files to the Bucket
      amazon.aws.s3_object:
        aws_access_key: "{{ aws_id }}"
        aws_secret_key: "{{ aws_key }}"
        region: "{{ aws_region }}"
        bucket: ansiblebucket2
        object: Playbooks/aws_iam.yml
        src: /home/test/Playbooks/aws_iam.yml
        mode: put
      register: copy_files

    - name: Output of Bucket Creation
      ansible.builtin.debug:
        var: create_bucket

    - name: Output of File Upload
      ansible.builtin.debug:
        var: copy_files
