---
# EC2_AMI Example for creating a basic AMI template from an existing image
- hosts: localhost
  connection: local
  remote_user: test
  become: yes
  gather_facts: no
  vars_files:
    - files/awscreds.yml
  tasks:
    - name: Basic Provisioning of an AMI from our Instance
      amazon.aws.ec2_ami:
        aws_access_key: "{{ aws_id }}"
        aws_secret_key: "{{ aws_key }}"
        region: "{{ aws_region }}"
        instance_id: i-1da8b9d9
        wait: no
        name: mynewami
        tags:
          Name: MyNewAMI
          Service: TestAMIService
      register: instance
