---
# EC2 SNAPSHOT MODULE EXAMPLE
- hosts: localhost
  connection: local
  remote_user: test
  become: yes
  gather_facts: no
  vars_files: 
    - files/awscreds.yml
  tasks: 
    - name: Delete a snapshot using snapshot ID
      amazon.aws.ec2_snapshot:
        aws_access_key: "{{ aws_id }}"
        aws_secret_key: "{{ aws_key }}"
        region: "{{ aws_region }}"
        snapshot_id: snap-707a342a
        state: absent
        wait: no
      register: snapshot
