---
# EC2 METRIC ALARM MODULE EXAMPLE
- hosts: localhost
  connection: local
  remote_user: test
  become: yes
  gather_facts: no
  vars_files:
    - files/awscreds.yml

  tasks:
    - name: Create a Basic CPU Alarm
      amazon.aws.cloudwatch_metric_alarm:
        aws_access_key: "{{ aws_id }}"
        aws_secret_key: "{{ aws_key }}"
        region: "{{ aws_region }}"
        state: present
        name: OurFirstAlarmTest
        metric_name: "CPUUtilization"
        namespace: "AWS/EC2"
        statistic: "Average"
        comparison_operator: ">="
        threshold: 25.0
        period: 300
        evaluation_periods: 6
        unit: "Percent"
        alarm_description: "This alarm fires when CPU is greater than 25% for 30 minutes"
        dimensions:
          InstanceId: "i-1da8b9d9"
      register: cloudwatch_alarm

    - name: Display Alarm Creation Output
      ansible.builtin.debug:
        var: cloudwatch_alarm
