---
# EC2_KEY MODULE EXAMPLE (Updated for Ansible 2.17)
- hosts: localhost
  connection: local
  remote_user: test
  become: yes
  gather_facts: no
  vars_files:
    - files/awscreds.yml

  tasks:
    - name: Delete an existing AWS Key Pair - MyKeyPairTestAWS
      amazon.aws.ec2_key:
        aws_access_key: "{{ aws_id }}"
        aws_secret_key: "{{ aws_key }}"
        name: MyKeyPairTestAWS
        region: us-west-2
        state: absent
